Work_Intergrated_Learning/Areas/Admin/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Work_Intergrated_Learning.Data;
using Work_Intergrated_Learning.Models;

namespace Work_Intergrated_Learning.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DepartmentController : Controller
    {
        private readonly WilDbContext context;

        public DepartmentController(WilDbContext context)
        {
            this.context = context;
        }


        //GET /admin/department
        public async Task<IActionResult> Index()
        {
            return View(await context.Departments.OrderBy(x => x.Sorting).ToListAsync());

        }
        //GET /admin/faculties/create 
        public IActionResult Create() => View();

        //Post /admin/department/create 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Department department)
        {
            if (ModelState.IsValid)
            {
                department.Slug = department.DepName.ToLower().Replace(" ", "-");
                department.Sorting = 100;

                var slug = await context.Faculties.FirstOrDefaultAsync(x => x.Slug == department.Slug);
                if (slug != null)
                {
                    ModelState.AddModelError("", "The Department already exists.");
                    return View(department);
                }

                context.Add(department);
                await context.SaveChangesAsync();

                TempData["Success"] = "The Department has been added";

                return RedirectToAction("Index");
            }
            return View(department);
        }

        //GET /admin/department/Edit
        public async Task<IActionResult> Edit(int Id)
        {
            Department department = await context.Departments.FindAsync(Id);
            if (department == null)
                return NotFound();

            return View(department);

        }

        //POST /admin/department/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Department department)
        {
            if (ModelState.IsValid)
            {
                department.Slug = department.DepName.ToLower().Replace(" ", "-");


                var slug = await context.Departments.Where(x => x.Id != id).FirstOrDefaultAsync(x => x.Slug == department.Slug);
                if (slug != null)
                {
                    ModelState.AddModelError("", "The Department already exists.");
                    return View(department);
                }

                context.Update(department);
                await context.SaveChangesAsync();

                TempData["Success"] = "The Department has been edited";

                return RedirectToAction("Edit", new { id });
            }
            return View(department);
        }

        //GET /admin/department/Delete
        public async Task<IActionResult> Delete(int Id)
        {
            Department department = await context.Departments.FindAsync(Id);
            if (department == null)
            {
                TempData["Error"] = "The Department does not exist";
            }
            else
            {
                context.Departments.Remove(department);
                await context.SaveChangesAsync();

                TempData["Success"] = "The Department has been deleted";
            }

            return RedirectToAction("Index");

        }


    }
}

Work_Intergrated_Learning/Areas/Admin/Controllers/FacultiesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Work_Intergrated_Learning.Data;
using Work_Intergrated_Learning.Models;

namespace Work_Intergrated_Learning.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FacultiesController : Controller
    {

        private readonly WilDbContext context;

        public FacultiesController(WilDbContext context)
        {
            this.context = context;
        }

        //GET /admin/faculties
        public async Task<IActionResult> Index()
        {
            return View(await context.Faculties.OrderBy(x => x.Sorting).ToListAsync());

        }
        //GET /admin/faculties/create 
        public IActionResult Create() => View();

        //Post /admin/faculties/create 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                faculty.Slug = faculty.FacultyName.ToLower().Replace(" ", "-");
                faculty.Sorting = 100;

                var slug = await context.Faculties.FirstOrDefaultAsync(x => x.Slug == faculty.Slug);
                if (slug != null)
                {
                    ModelState.AddModelError("", "The faculty already exists.");
                    return View(faculty);
                }

                context.Add(faculty);
                await context.SaveChangesAsync();

                TempData["Success"] = "The Faculty has been added";

                return RedirectToAction("Index");
            }
            return View(faculty);
        }

        //GET /admin/faculties/Edit
        public async Task<IActionResult> Edit(int Id)
        {
            Faculty faculty = await context.Faculties.FindAsync(Id);
            if (faculty == null)
                return NotFound();

            return View(faculty);

        }

        //POST /admin/faculties/Edit
       [HttpPost]
       [ValidateAntiForgeryToken]
       public async Task<IActionResult> Edit(int id,Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                faculty.Slug = faculty.FacultyName.ToLower().Replace(" ", "-");


                var slug = await context.Faculties.Where(x => x.Id != id).FirstOrDefaultAsync(x => x.Slug == faculty.Slug);
                if (slug != null)
                {
                    ModelState.AddModelError("", "The Faculty already exists.");
                    return View(faculty);
                }

                context.Update(faculty);
                await context.SaveChangesAsync();

                TempData["Success"] = "The Faculty has been edited";

                return RedirectToAction("Edit", new {id});
            }
            return View(faculty);
        }

        //GET /admin/faculties/Delete
        public async Task<IActionResult> Delete(int Id)
        {
            Faculty faculty = await context.Faculties.FindAsync(Id);
            if (faculty == null)
            {
                TempData["Error"] = "The Faculty does not exist";
            }
            else
            {
                context.Faculties.Remove(faculty);
                await context.SaveChangesAsync();

                TempData["Success"] = "The Faculty has been deleted";
            }

            return RedirectToAction("Index");

        }





    }

    
}

Work_Intergrated_Learning/Controllers/JobsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Work_Intergrated_Learning.Data;

namespace Work_Intergrated_Learning.Controllers
{
   // [Authorize]
    public class JobsController : Controller
    {
        private readonly WilDbContext context;
        public JobsController(WilDbContext context)
        {
            this.context = context;
        }

        //GET /Jobs
        public async Task<IActionResult> Index()
        {
            return View(await context.Jobs.OrderBy(x => x.Sorting).ToListAsync());

        }


    }
}

Work_Intergrated_Learning/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin Area</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" target="_blank">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Faculties" asp-action="Index">Faculties</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Jobs" asp-action="Index">Jobs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
     
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Work_Intergrated_Learning/Areas/Admin/Views/Shared/_NotificationPartial.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-success notification">
        @TempData["Success"]
    </div>
}
@if (TempData["Error"] != null)
{
    <div class="alert alert-danger notification">
        @TempData["Error"]
    </div>
}