Work_Intergrated_Learning/Controllers/JobsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Work_Intergrated_Learning.Data;

namespace Work_Intergrated_Learning.Controllers
{
   // [Authorize]
    public class JobsController : Controller
    {
        private readonly WilDbContext context;
        public JobsController(WilDbContext context)
        {
            this.context = context;
        }

        //GET /Jobs
        public async Task<IActionResult> Index()
        {
            return View(await context.Jobs.OrderBy(x => x.Sorting).ToListAsync());

        }


    }
}

Work_Intergrated_Learning/Data/FacultiesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Work_Intergrated_Learning.Models;

namespace Work_Intergrated_Learning.Data
{
    public class FacultiesViewComponent : ViewComponent
    {
        private readonly WilDbContext context;

        public FacultiesViewComponent(WilDbContext context)
        {
            this.context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var faculties = await GetFacultiesAsync();
            return View(faculties);
        }

        private Task<List<Faculty>> GetFacultiesAsync()
        {
            return context.Faculties.OrderBy(x => x.Sorting).ToListAsync();
        }

    }
}

Work_Intergrated_Learning/Data/MainMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Work_Intergrated_Learning.Models;

namespace Work_Intergrated_Learning.Data
{
    public class MainMenuViewComponent : ViewComponent
    {
        private readonly WilDbContext context;

        public MainMenuViewComponent(WilDbContext context)
        {
            this.context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var pages = await GetPagesAsync();
            return View(pages);
        }

        private Task<List<Page>> GetPagesAsync()
        {
            return context.Pages.OrderBy(x => x.Sorting).ToListAsync();
        }
            
    }
}

Work_Intergrated_Learning/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Work_Intergrated_Learning</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  navbar-light bg-white border-bottom box-shadow mb-1">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Jobs" asp-action="Index">
                    <img src="/media/images/CUT.jpg" alt="CUT Logo" style="width:140px;height:70px" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        @if (User.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Edit" class="btn btn-primary">Profile</a>
                            </li>
                            <li class="nav-item ml-1">
                                <a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Log Out</a>
                            </li>
                        }
                        else
                        {

                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Login" class="btn btn-primary">Login</a>
                            </li>
                            <li class="nav-item ml-1">
                                <a asp-controller="Account" asp-action="Register" class="btn btn-success">Register</a>
                            </li>
                        }


                    </ul>
                    @*<ul class="navbar-nav flex-grow-1">
                            @await Component.InvokeAsync("MainMenu")
                        </ul>*@

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="row">
                <div class="col-3">
                    @await Component.InvokeAsync("Faculties")
                </div>
                <div class="col">
                    @RenderBody()
                </div>

            </div>

        </main>
    </div>




    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>